name=Wireless Mesh
version=1.0.2
author=William Giles
maintainer=William Giles <me@williamgiles.co.nz>
sentence=A library for wireless mesh networking
paragraph=A library for wireless mesh networking
category=Networking
url=https://github.com/dcralph/wireless_mesh
architectures=esp32
depends=ESP32